# 配置数据库链接
spring:
  application:
    name: nacos-msg-task-web
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    # 数据库连接池使用durid
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据库版本高于6.0以上时使用下列代码
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库版本低于6.0时使用下列代码
    # driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testall?useUnicode=true&characterEncoding=utf8
    username: root
    password:

# dubbo 配置作用是为了标识从哪里取调用的服务
dubbo:
  protocol:
    port: -1
    name: dubbo
  consumer:
    check: false
  registry:
    address: nacos://localhost:8848